Vagrant.configure("2") do |config|
    config.vm.box = "#{ENV['DISTR']}/#{ENV['OS']}"

    config.vm.provider "libvirt" do |v|
        v.memory = ENV['RAM'].to_i  # Set the RAM for libvirt
        v.cpus = ENV['CPU'].to_i    # Set the number of CPUs
        v.features = ["apic"]       # Enable IOAPIC equivalent in libvirt
        v.uri = "qemu:///session"
        v.connect_via_ssh = false
    end

    config.vm.define 'ubuntu'

    config.vm.hostname = "host4test"

    if ENV['TEST_CASE'] != '--production-install'
       config.vm.provision "file", source: "../../../DocSpace-buildtools/install/OneClickInstall/.", destination: "/tmp/docspace/"
    end

    config.vm.provision "file", source: "../../../DocSpace-buildtools/install/common/systemd/build.sh", destination: "/tmp/docspace/build.sh"
    config.vm.provision "shell", path: './install.sh', :args => "#{ENV['DOWNLOAD_SCRIPT']} #{ENV['TEST_REPO']} #{ENV['ARGUMENTS']}"

    # Prevent SharedFoldersEnableSymlinksCreate errors
    config.vm.synced_folder ".", "/vagrant", disabled: true
end
