Vagrant.configure("2") do |config|
    config.vm.box = "#{ENV['DISTR']}/#{ENV['OS']}"
  
    # Define the VM
    config.vm.define 'test_vm' do |vm_config|
      vm_config.vm.hostname = "host4test"
  
      # Prevent SharedFoldersEnableSymlinksCreate errors
      vm_config.vm.synced_folder ".", "/vagrant", disabled: true
  
      # Configure VM provider settings
      vm_config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "#{ENV['RAM']}"] # Total RAM
        v.customize ["modifyvm", :id, "--cpus", "#{ENV['CPU']}"]   # Total CPU
        v.customize ["modifyvm", :id, "--ioapic", "on"]
  
      # Provisioning steps
      if ENV['TEST_CASE'] != '--production-install'
        vm_config.vm.provision "file", source: "../../../DocSpace-buildtools/install/OneClickInstall/.", destination: "/tmp/docspace/"
      end
  
      vm_config.vm.provision "file", source: "../../../DocSpace-buildtools/install/common/systemd/build.sh", destination: "/tmp/docspace/build.sh"
  
      # Run the installation script
      vm_config.vm.provision "shell", path: './install.sh', args: "#{ENV['DOWNLOAD_SCRIPT']} #{ENV['TEST_REPO']} #{ENV['ARGUMENTS']}"
    end
  end
  
