name: 4testing multiarch-build

on:
  repository_dispatch:
    types:
      - cron-trigger-action
      - config-trigger-action
      - client-trigger-action
      - server-trigger-action

jobs:
  prepare-branches:
    runs-on: ubuntu-latest
    outputs: 
      branches: ${{ steps.prepare.outputs.branches }}
    steps:
      - name: prepare branches
        id: prepare
        env: 
          var: ${{ fromJSON(github.event.client_payload.branches) }}
        run: |
          echo "branches=${{ join(github.event.client_payload.branches) }}" >> "$GITHUB_OUTPUT"

  call-reusable-build:
    needs: prepare-branches
    uses: danilapog/DocSpace-buildtools/.github/workflows/reusable-build.yml@master
    with:
      payload-branches: '${{ needs.prepare-branches.outputs.branches }}'
      dispatch-type: ${{ github.event.action }}
