name: 4testing multiarch-build

on:
  repository_dispatch:
    types:
      - cron-trigger-action
      - config-trigger-action
      - client-trigger-action
      - server-trigger-action

jobs:
  prepare-branches:
    runs-on: ubuntu-latest
    steps:
      - name: prepare branches
        env: 
          var: ${{ join(github.event.client_payload.branches) }}
        run: |
          echo ${var}
          echo "BRANCHES=(${var})" >> "$GITHUB_ENV"
          echo "value=1" >> "$GITHUB_ENV"

  prepare-branches1:
    runs-on: ubuntu-latest
    steps:
      - name: prepare branches
        env: 
          var: ${{ join(github.event.client_payload.branches) }}
        run: |
          echo ${{ env.BRANCHES }}
          
  call-reusable-build:
    uses: danilapog/DocSpace-buildtools/.github/workflows/reusable-build.yml@master
    with:
      payload-branches: ${{ join(github.event.client_payload.branches) }}
      dispatch-type: ${{ github.event.action }}
